#!/bin/bash

echo "🔗 Création de l'alias 'backup-tool'..."
ln -sf /usr/local/bin/ubuntu_backup_restore /usr/local/bin/backup-tool

chmod +x /usr/local/bin/backup-tool

echo "✅ L'outil est maintenant accessible via la commande : backup-tool"